top_srcdir   = /bottlenecks/rubbos/app/httpd-2.0.64
top_builddir = /bottlenecks/rubbos/app/httpd-2.0.64
srcdir       = /bottlenecks/rubbos/app/httpd-2.0.64/modules/cache
builddir     = /bottlenecks/rubbos/app/httpd-2.0.64/modules/cache
VPATH        = /bottlenecks/rubbos/app/httpd-2.0.64/modules/cache

include $(top_srcdir)/build/special.mk

