top_srcdir   = /bottlenecks/rubbos/app/httpd-2.0.64
top_builddir = /bottlenecks/rubbos/app/httpd-2.0.64
srcdir       = /bottlenecks/rubbos/app/httpd-2.0.64/modules/filters
builddir     = /bottlenecks/rubbos/app/httpd-2.0.64/modules/filters
VPATH        = /bottlenecks/rubbos/app/httpd-2.0.64/modules/filters

include $(top_srcdir)/build/special.mk

