top_srcdir   = /bottlenecks/rubbos/app/httpd-2.0.64
top_builddir = /bottlenecks/rubbos/app/httpd-2.0.64
srcdir       = /bottlenecks/rubbos/app/httpd-2.0.64/os/beos
builddir     = /bottlenecks/rubbos/app/httpd-2.0.64/os/beos
VPATH        = /bottlenecks/rubbos/app/httpd-2.0.64/os/beos

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = os.c beosd.c

include $(top_srcdir)/build/ltlib.mk
