top_srcdir   = /bottlenecks/rubbos/app/httpd-2.0.64
top_builddir = /bottlenecks/rubbos/app/httpd-2.0.64
srcdir       = /bottlenecks/rubbos/app/httpd-2.0.64/srclib
builddir     = /bottlenecks/rubbos/app/httpd-2.0.64/srclib
VPATH        = /bottlenecks/rubbos/app/httpd-2.0.64/srclib

SUBDIRS = pcre
BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
