top_srcdir   = /bottlenecks/rubbos/app/httpd-2.0.64
top_builddir = /bottlenecks/rubbos/app/httpd-2.0.64
srcdir       = /bottlenecks/rubbos/app/httpd-2.0.64/modules/loggers
builddir     = /bottlenecks/rubbos/app/httpd-2.0.64/modules/loggers
VPATH        = /bottlenecks/rubbos/app/httpd-2.0.64/modules/loggers

include $(top_srcdir)/build/special.mk

