top_srcdir   = /bottlenecks/rubbos/app/httpd-2.0.64
top_builddir = /bottlenecks/rubbos/app/httpd-2.0.64
srcdir       = /bottlenecks/rubbos/app/httpd-2.0.64/modules/echo
builddir     = /bottlenecks/rubbos/app/httpd-2.0.64/modules/echo
VPATH        = /bottlenecks/rubbos/app/httpd-2.0.64/modules/echo

include $(top_srcdir)/build/special.mk

