top_srcdir   = /bottlenecks/rubbos/app/httpd-2.0.64
top_builddir = /bottlenecks/rubbos/app/httpd-2.0.64
srcdir       = /bottlenecks/rubbos/app/httpd-2.0.64/os/unix
builddir     = /bottlenecks/rubbos/app/httpd-2.0.64/os/unix
VPATH        = /bottlenecks/rubbos/app/httpd-2.0.64/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
