top_srcdir   = /bottlenecks/rubbos/app/httpd-2.0.64
top_builddir = /bottlenecks/rubbos/app/httpd-2.0.64
srcdir       = /bottlenecks/rubbos/app/httpd-2.0.64/modules/experimental
builddir     = /bottlenecks/rubbos/app/httpd-2.0.64/modules/experimental
VPATH        = /bottlenecks/rubbos/app/httpd-2.0.64/modules/experimental
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
