top_srcdir   = /bottlenecks/rubbos/app/httpd-2.0.64
top_builddir = /bottlenecks/rubbos/app/httpd-2.0.64
srcdir       = /bottlenecks/rubbos/app/httpd-2.0.64/modules/generators
builddir     = /bottlenecks/rubbos/app/httpd-2.0.64/modules/generators
VPATH        = /bottlenecks/rubbos/app/httpd-2.0.64/modules/generators

include $(top_srcdir)/build/special.mk

