top_srcdir   = /bottlenecks/rubbos/app/httpd-2.0.64
top_builddir = /bottlenecks/rubbos/app/httpd-2.0.64
srcdir       = /bottlenecks/rubbos/app/httpd-2.0.64/server/mpm
builddir     = /bottlenecks/rubbos/app/httpd-2.0.64/server/mpm
VPATH        = /bottlenecks/rubbos/app/httpd-2.0.64/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
