top_srcdir   = /bottlenecks/rubbos/app/httpd-2.0.64
top_builddir = /bottlenecks/rubbos/app/httpd-2.0.64
srcdir       = /bottlenecks/rubbos/app/httpd-2.0.64/os
builddir     = /bottlenecks/rubbos/app/httpd-2.0.64/os
VPATH        = /bottlenecks/rubbos/app/httpd-2.0.64/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
