top_srcdir   = /bottlenecks/rubbos/app/httpd-2.0.64
top_builddir = /bottlenecks/rubbos/app/httpd-2.0.64
srcdir       = /bottlenecks/rubbos/app/httpd-2.0.64/modules/mappers
builddir     = /bottlenecks/rubbos/app/httpd-2.0.64/modules/mappers
VPATH        = /bottlenecks/rubbos/app/httpd-2.0.64/modules/mappers

include $(top_srcdir)/build/special.mk

