top_srcdir   = /bottlenecks/rubbos/app/httpd-2.0.64
top_builddir = /bottlenecks/rubbos/app/httpd-2.0.64
srcdir       = /bottlenecks/rubbos/app/httpd-2.0.64/modules/http
builddir     = /bottlenecks/rubbos/app/httpd-2.0.64/modules/http
VPATH        = /bottlenecks/rubbos/app/httpd-2.0.64/modules/http

include $(top_srcdir)/build/special.mk

