top_srcdir   = /bottlenecks/rubbos/app/httpd-2.0.64
top_builddir = /bottlenecks/rubbos/app/httpd-2.0.64
srcdir       = /bottlenecks/rubbos/app/httpd-2.0.64/server/mpm/worker
builddir     = /bottlenecks/rubbos/app/httpd-2.0.64/server/mpm/worker
VPATH        = /bottlenecks/rubbos/app/httpd-2.0.64/server/mpm/worker

LTLIBRARY_NAME    = libworker.la
LTLIBRARY_SOURCES = worker.c fdqueue.c pod.c

include $(top_srcdir)/build/ltlib.mk
