top_srcdir   = /bottlenecks/rubbos/app/httpd-2.0.64
top_builddir = /bottlenecks/rubbos/app/httpd-2.0.64
srcdir       = /bottlenecks/rubbos/app/httpd-2.0.64/modules/metadata
builddir     = /bottlenecks/rubbos/app/httpd-2.0.64/modules/metadata
VPATH        = /bottlenecks/rubbos/app/httpd-2.0.64/modules/metadata

include $(top_srcdir)/build/special.mk

