top_srcdir   = /bottlenecks/rubbos/app/httpd-2.0.64
top_builddir = /bottlenecks/rubbos/app/httpd-2.0.64
srcdir       = /bottlenecks/rubbos/app/httpd-2.0.64/os/os2
builddir     = /bottlenecks/rubbos/app/httpd-2.0.64/os/os2
VPATH        = /bottlenecks/rubbos/app/httpd-2.0.64/os/os2

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = util_os2.c

include $(top_srcdir)/build/ltlib.mk
